name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cloudflare Deploy Hook
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/workers/builds/deploy_hooks/648eb968-63ee-460b-8f81-a2160f62eb85"
